# Generated by Django 3.2 on 2022-01-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('cat_des', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('company_address', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.area')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45)),
                ('is_approved', models.IntegerField(blank=True, null=True)),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hardwares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=75)),
                ('tot_amount', models.IntegerField()),
                ('customer_idcustomer', models.ForeignKey(db_column='customer_idCustomer', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('product_desc', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('rent_per_day', models.FloatField(blank=True, null=True)),
                ('rent_per_week', models.FloatField(blank=True, null=True)),
                ('rent_per_month', models.FloatField(blank=True, null=True)),
                ('deposit', models.IntegerField()),
                ('delivery_pickup_charges', models.IntegerField()),
                ('brand_idbrand', models.ForeignKey(db_column='brand_idbrand', on_delete=django.db.models.deletion.CASCADE, to='accounts.brand')),
                ('category_idcategory', models.ForeignKey(db_column='category_idcategory', on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deposit_amount', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('cheque_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('product_idproduct', models.ForeignKey(blank=True, db_column='product_idproduct', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tot_amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=45)),
                ('bank_ref_num', models.CharField(max_length=45)),
                ('order_idorder', models.ForeignKey(db_column='order_idorder', on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
                ('payment_method_idpayment_method', models.ForeignKey(db_column='payment_method_idpayment_method', on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_details', models.CharField(blank=True, max_length=45, null=True)),
                ('hardwares_idhardware', models.ForeignKey(db_column='hardwares_idhardware', on_delete=django.db.models.deletion.CASCADE, to='accounts.hardwares')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('customer_idcustomer', models.ForeignKey(db_column='customer_idCustomer', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('product_idproduct', models.ForeignKey(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.djangocontenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.IntegerField()),
                ('delivery_boy_iddelivery_boy', models.ForeignKey(db_column='delivery_boy_idDelivery_boy', on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryboy')),
                ('order_idorder', models.ForeignKey(db_column='order_idorder', on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('product_idproduct', models.ForeignKey(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
                ('user_iduser', models.ForeignKey(db_column='user_idUser', on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='state_idstate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=45)),
                ('state_idstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='productimg_idproductimg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productimg'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_idcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_idcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.djangocontenttype'),
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.authpermission')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.CreateModel(
            name='ProductHasOrder',
            fields=[
                ('product_idproduct', models.OneToOneField(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.product')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('delivery_pickup_charge', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_status', models.CharField(max_length=15)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('given_deposit_iddeposit', models.ForeignKey(blank=True, db_column='given_deposit_iddeposit', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.returndeposit')),
                ('order_idorder', models.ForeignKey(db_column='order_idorder', on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHasOffers',
            fields=[
                ('product_idproduct', models.OneToOneField(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.product')),
                ('offers_id_offer', models.ForeignKey(db_column='offers_id_offer', on_delete=django.db.models.deletion.CASCADE, to='accounts.offers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHasHardwares',
            fields=[
                ('product_idproduct', models.OneToOneField(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.product')),
                ('hardwares_idhardware', models.ForeignKey(db_column='hardwares_idhardware', on_delete=django.db.models.deletion.CASCADE, to='accounts.hardwares')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeHasHardwares',
            fields=[
                ('customize_idcustomize', models.OneToOneField(db_column='customize_idcustomize', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customize')),
                ('hardwares_idhardware', models.ForeignKey(db_column='hardwares_idhardware', on_delete=django.db.models.deletion.CASCADE, to='accounts.hardwares')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('customer_idcustomer', models.OneToOneField(db_column='customer_idCustomer', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customer')),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('delivery_pickup_charges', models.IntegerField()),
                ('product_idproduct', models.ForeignKey(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='AreaHasDeliveryBoy',
            fields=[
                ('area_idarea', models.OneToOneField(db_column='area_idarea', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.area')),
                ('delivery_boy_iddelivery_boy', models.ForeignKey(db_column='delivery_boy_idDelivery_boy', on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryboy')),
            ],
        ),
    ]
