# Generated by Django 3.2 on 2022-01-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state_idstate',
            new_name='state',
        ),
    ]
