# Generated by Django 3.2 on 2022-02-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=350)),
                ('user', models.ForeignKey(db_column='user_idUser', on_delete=django.db.models.deletion.CASCADE, to='accounts.authuser')),
            ],
        ),
    ]
