# Generated by Django 3.2 on 2022-02-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='product_name',
            field=models.CharField(max_length=75),
        ),
    ]
