# Generated by Django 3.2 on 2022-01-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_areahasdeliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHasDeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.area')),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryboy')),
            ],
        ),
    ]
