# Generated by Django 3.2 on 2022-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deliverypickup_dutydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypickup',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
