# Generated by Django 3.2 on 2022-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliverypickup_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
