# Generated by Django 4.0.2 on 2022-03-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_delivery_pickup_charges_cart_delivery_pickup_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_pickup_charges',
            new_name='delivery_pickup_charge',
        ),
    ]
