# Generated by Django 3.2 on 2022-01-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_areahasdeliveryboy_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthasorder',
            name='deliveryboy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.deliveryboy'),
        ),
    ]
