# Generated by Django 4.0.2 on 2022-03-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_delivery_pickup_charges_product_delivery_pickup_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='delivery_pickup_charge',
            new_name='delivery_pickup_charges',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='rent_price',
            new_name='rent_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delivery_pickup_charge',
            new_name='delivery_pickup_charges',
        ),
    ]
