# Generated by Django 3.2 on 2022-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='users/avatar-png-1-original.png', upload_to='users/'),
        ),
    ]
