# Generated by Django 3.2 on 2022-02-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customize_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customize',
            old_name='user',
            new_name='customer',
        ),
    ]
