# Generated by Django 3.2 on 2022-02-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_area_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('declined', 'declined'), ('accepted', 'accepted')], default='pending', max_length=10, null=True),
        ),
    ]
