# Generated by Django 3.2 on 2022-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_customize_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
