# Generated by Django 4.0.2 on 2022-03-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_delivery_pickup_charge_cart_delivery_pickup_charges_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producthasorder',
            unique_together=set(),
        ),
    ]
