# Generated by Django 3.2 on 2022-01-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='contact',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='image',
            field=models.ImageField(default='users/avatar-png-1-original.png', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(default='users/avatar-png-1-original.png', upload_to='users/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
