# Generated by Django 4.0.2 on 2022-03-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_producthasorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrating',
            name='orderProduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.producthasorder'),
            preserve_default=False,
        ),
    ]
