# Generated by Django 3.2 on 2022-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customize_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
