# Generated by Django 3.2 on 2022-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220111_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
