# Generated by Django 4.1.6 on 2024-04-20 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feedbackrating_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrating',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
