# Generated by Django 3.2 on 2022-02-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customize_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='pending',
            field=models.CharField(blank=True, default='pending', max_length=10, null=True),
        ),
    ]
