# Generated by Django 3.2 on 2022-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/brand/'),
            preserve_default=False,
        ),
    ]
