# Generated by Django 3.2 on 2022-01-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, default='users/avatar-png-1-original.png', null=True, upload_to='users/'),
        ),
    ]
