# Generated by Django 3.2 on 2022-01-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_admin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_panding',
            field=models.IntegerField(default=True),
        ),
    ]
