# Generated by Django 3.2 on 2022-01-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_is_panding'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
            preserve_default=False,
        ),
    ]
