# Generated by Django 3.2 on 2022-02-06 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_pending_customize_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=150)),
                ('otp', models.IntegerField(max_length=6)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
