# Generated by Django 3.2 on 2022-01-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220118_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_des',
        ),
        migrations.AlterField(
            model_name='category',
            name='productimg_idproductimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productimg'),
        ),
    ]
