# Generated by Django 3.2 on 2022-01-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220120_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImg',
            new_name='Image',
        ),
    ]
