# Generated by Django 3.2 on 2022-02-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypickup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverypickup', to='accounts.producthasorder'),
        ),
    ]
