# Generated by Django 3.2 on 2022-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_productimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='productimg_idproductimg',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
