# Generated by Django 3.2 on 2022-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_category_subcategory_idcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthasorder',
            name='cancelpay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
