# Generated by Django 3.2 on 2022-02-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_producthasorder_cancelpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthasorder',
            name='cancelpay',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelpay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
