# Generated by Django 3.2 on 2022-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220212_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelpay',
        ),
        migrations.AddField(
            model_name='producthasorder',
            name='cancelpay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
