# Generated by Django 3.2 on 2022-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220212_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthasorder',
            name='returndeposite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
