# Generated by Django 3.2 on 2022-02-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_producthasorder_returndeposite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthasorder',
            name='returndeposite',
        ),
        migrations.AddField(
            model_name='order',
            name='returndeposite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
